mysql:
  host: 116.232.101.55
#  host: 127.0.0.1
  port: 3306
  password: jxc123456.
  username: root
  dbname:
    jxc: jxc
  maxIdleConn: 1
  maxOpenConn: 5
server:
  addr: "0.0.0.0:888"
  autoMigrate: true